version: '2.27'

services:
  app:
    image: nestjs-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - nest-network

  db-pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=mainUser
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nest-network

  pg-admin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - db-pg
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 8080:80
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge
